---

- name: Install required packages
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened:
    - '{{ whereami__base_packages }}'
  tags: [ 'role::whereami:pkgs', 'role::whereami:install' ]

- name: Create directory for additional scripts
  file:
    path: '/usr/local/share/whereami'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  when: (whereami__install_additional_scripts|d([]))
  tags: [ 'role::whereami:install' ]

- name: Install additional scripts for whereami
  copy:
    src: 'usr/local/share/whereami/{{ item }}'
    dest: '/usr/local/share/whereami/{{ item }}'
    mode: '0754'
    owner: 'root'
    group: 'root'
  with_flattened: '{{ whereami__install_additional_scripts }}'
  tags: [ 'role::whereami:install' ]

- name: Install patched whereami
  copy:
    src: 'usr/local/bin/whereami'
    dest: '/usr/local/bin/whereami'
    mode: '0755'
    owner: 'root'
    group: 'root'
  when: whereami__install_patches
  tags: [ 'role::whereami:install' ]

  ## https://stackoverflow.com/a/28888474
- name: Test if Ansible is running in check mode
  command: /bin/true
  changed_when: False
  register: whereami__register_check_mode

- name: Save fact if Ansible is running in check mode in variable
  set_fact: check_mode={{ whereami__register_check_mode|skipped }}

- name: Install hook script to /etc/network/if-*.d/
  file:
    src: '/etc/network/if-pre-up.d/whereami'
    path: '{{ item.path }}'
    state: 'link'
    force: '{{ check_mode|d() | bool }}'
    mode: '0755'
    owner: 'root'
    group: 'root'
  when: item.when|d(True) | bool
  tags: [ 'role::whereami:install' ]
  with_items:
    - path: '/etc/network/if-up.d/whereami'
      when: '{{ whereami__install_to_if_up_d | bool }}'
    - path: '/etc/network/if-post-down.d/whereami'
      when: '{{ whereami__install_to_if_post_down_d | bool }}'

- name: Remove hook script from /etc/network/if-*.d/
  file:
    path: '{{ item.path }}'
    state: 'absent'
  when: not (item.when|d(True) | bool)
  tags: [ 'role::whereami:install' ]
  with_items:
    - path: '/etc/network/if-up.d/whereami'
      when: '{{ whereami__install_to_if_up_d | bool }}'
    - path: '/etc/network/if-post-down.d/whereami'
      when: '{{ whereami__install_to_if_post_down_d | bool }}'

- name: Configure detection rules
  template:
    src: 'etc/whereami/detect.conf.j2'
    dest: '/etc/whereami/detect.conf'
    mode: '{{ whereami__configuration_mode }}'
    owner: 'root'
    group: 'root'
  tags: [ 'role::whereami:config' ]

- name: Configure whereami actions
  template:
    src: 'etc/whereami/whereami.conf.j2'
    dest: '/etc/whereami/whereami.conf'
    mode: '{{ whereami__configuration_mode }}'
    owner: 'root'
    group: 'root'
  tags: [ 'role::whereami:config' ]
