#!/bin/bash
## @license AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
## @author Copyright (C) 2015 Robin Schneider <ypid@riseup.net>
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU Affero General Public License as
## published by the Free Software Foundation, version 3 of the
## License.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU Affero General Public License for more details.
##
## You should have received a copy of the GNU Affero General Public License
## along with this program.  If not, see <https://www.gnu.org/licenses/>.
##
## Test against device information network-manager can provide.
##
## Check if wlan0 is currently connected to "connection_name":
##   ./testnm-device "wlan0,GENERAL\.CONNECTION:connection_name"
##
## Check if wlan0 is has been (auto-)configured with this DNS server:
##  ./testnm-device 'wlan0,IP4.DNS\[\d+\]:192\.0\.2\.2'
##
## Check if wlan0 is has been (auto-)configured with this domain:
## ./testnm-device 'wlan0,IP4.DOMAIN\[\d+\]:your-domain.tld'

# Turn on execution tracing, for debugging...
[ "$DEBUGWHEREAMI" = "1" ] && set -o xtrace

case "$1" in
    *,*)
        IFACE="${1/,*}"
        SEARCH_PATTERN="${1/*,}"
        ;;
    *)
        SEARCH_PATTERN="${1}"
        ;;
esac

if [ -z "$IFACE" ]
then
    # We can also set $INTERFACE externally and that will be used as the default.
    INTERFACE="${INTERFACE:-"eth0"}"
else
    INTERFACE="${IFACE}"
fi
if [ "$INTERFACE" == 'all' ]
then
    INTERFACE=''
fi

nmcli --terse device show $INTERFACE | grep --quiet --perl-regexp "$SEARCH_PATTERN" && exit 0

exit 1
