---

- name: Setup and configure whereami
  hosts: [ 'ypid_service_whereami' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: ypid.whereami
      tags: [ 'role::whereami' ]
